import { Dish } from "./store/types";

export const dishes: Dish[] = [
  {
    id: "1",
    name: "fries",
    category: "Starter",
    price: 25,
    info: "Appropiate for two",
  },
  {
    id: "2",
    name: "chilly potato",
    category: "Starter",
    price: 20,
    info: "Appropiate for one",
  },
  {
    id: "3",
    name: "pasta",
    category: "Starter",
    price: 20,
    info: "Appropiate for one",
  },
  {
    id: "4",
    name: "Chicken wings",
    category: "Starter",
    price: 20,
    info: "Only one person",
  },
  {
    id: "5",
    name: "Chicken Gravy",
    category: "Main Course",
    price: 100,
    info: "Two person",
  },
  {
    id: "6",
    name: "Mutton Gravy",
    category: "Main Course",
    price: 100,
    info: "Two person",
  },
  {
    id: "7",
    name: "Paneer Gravy",
    category: "Main Course",
    price: 200,
    info: "Two person",
  },
  {
    id: "8",
    name: "Fried Rice",
    category: "Main Course",
    price: 200,
    info: "Two person",
  },
  {
    id: "9",
    name: "Ice Cream",
    category: "Dessert",
    price: 20,
    info: "One person",
  },
  {
    id: "10",
    name: "Cake",
    category: "Dessert",
    price: 20,
    info: "One person",
  },
  {
    id: "11",
    name: "Choco lava cake",
    category: "Dessert",
    price: 20,
    info: "One person",
  },
  {
    id: "12",
    name: "Beer",
    category: "Drinks",
    price: 20,
    info: "One person",
  },
  {
    id: "13",
    name: "Wine",
    category: "Drinks",
    price: 200,
    info: "One person",
  },
  {
    id: "14",
    name: "Mocktails",
    category: "Drinks",
    price: 200,
    info: "One person",
  },
];
